description: Start up fast react web apps with Vite.js
name: matter-web-vite
display-name: matter-web-vite
picture: stack.png
category: Frontend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility: # Put a list of technologies compatible with the stack
  - React
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies 
  - Typescript
  - Web
about: docs/about.md
use-cases:
  - title: Create Vite application
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml