name: web-react-vite-citric
description: Add citric on project vite
display-name: web-react-vite-citric
picture: plugin.png
category: frontend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - react
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - Typescript
  - Web
types:
  - app

hooks:
  - type: run
    trigger: before-render
    working-dir: app/
    linux:
      - echo Installing Citric Dependencies ...
      - npm install --dev @citric/core @citric/theme-types @citric/icons styled-components
    windows:
      - echo Installing Citric Dependencies ...
      - cmd /c npm install --dev @citric/core @citric/theme-types @citric/icons styled-components
    mac:
      - echo Installing Citric Dependencies ...
      - npm install --dev @citric/core @citric/theme-types @citric/icons styled-components

  - type: edit
    trigger: after-render
    path: app/src/main.tsx
    changes: 
      - search: 
          string: import
          insert-after: 
            snippet: snippets/imports.tsx
          when:
            not-exists-snippet: snippets/imports.tsx

      - search:
          string: "<AppRouting />"
          replace-by: 
            snippet: snippets/theme-provider.tsx
          when:
            not-exists-snippet: snippets/theme-provider.tsx

  - type: run
    trigger: after-render
    working-dir: app/src/pages/Home
    mac: 
      - rm index.tsx
      - touch index.tsx
    linux: 
      - rm index.tsx
      - touch index.tsx
    windows: 
      - del index.tsx
      - echo > index.tsx
  
  - type: edit
    trigger: after-render
    path: app/src/pages/Home/index.tsx
    changes : 
      - insert:
          line: 0
          snippet: snippets/home.tsx
          when: 
            not-exists-snippet: snippets/home.tsx
